// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAREnxgXK72Yj0qGogoBUhcTpRrZYkW20',
    appId: '1:471167409540:web:e30a29a94f4d8ac98391d1',
    messagingSenderId: '471167409540',
    projectId: 'parking-b03f0',
    authDomain: 'parking-b03f0.firebaseapp.com',
    storageBucket: 'parking-b03f0.appspot.com',
    measurementId: 'G-CPHCZTCT2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5yF_yKgJnJ47T-cbuNnP0Ph2Qcp6Y6iw',
    appId: '1:471167409540:android:9537eb224b8e8a568391d1',
    messagingSenderId: '471167409540',
    projectId: 'parking-b03f0',
    storageBucket: 'parking-b03f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBof0mQmYDWXW7CpxAq_Vht6uuzesyLf5g',
    appId: '1:471167409540:ios:a439c3a273f562698391d1',
    messagingSenderId: '471167409540',
    projectId: 'parking-b03f0',
    storageBucket: 'parking-b03f0.appspot.com',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBof0mQmYDWXW7CpxAq_Vht6uuzesyLf5g',
    appId: '1:471167409540:ios:a439c3a273f562698391d1',
    messagingSenderId: '471167409540',
    projectId: 'parking-b03f0',
    storageBucket: 'parking-b03f0.appspot.com',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAREnxgXK72Yj0qGogoBUhcTpRrZYkW20',
    appId: '1:471167409540:web:2c71d13d408ba7c08391d1',
    messagingSenderId: '471167409540',
    projectId: 'parking-b03f0',
    authDomain: 'parking-b03f0.firebaseapp.com',
    storageBucket: 'parking-b03f0.appspot.com',
    measurementId: 'G-LYJZ14QTNL',
  );
}
